cd "D:\Dropbox\Haiti\GAFSP Haiti\submission\final version\replication\data"

use panel_dataset_for_replication_allvar, clear 

# delimit ; 
keep
access_water_*
ag_income_*
agri_asso_*
agri_coop_*
allchem_*
allchem_spending_*
askloan_bank_*
askloaninp_bank_*
askloaninp_sara_*
assets_farm_ind_*
assets_hh_ind_*
assets_livst_ind1_*
assets_livst_ind2_*
bnk_*
compost_*
d_familylabor_*
d_growrice*
d_growrice_*
d_mult*
d_mult_cond_*
d_paidlabor_*
d_thinkben_*
d_unpaidlabor_*
DR_fem_work_HH_*
DR_male_adult_work_HH_*
DR_male_work_days_H
DR_male_work_HH_*
DR_tot_adult_work_HH_*
DR_tot_work_days_
DR_tot_work_days_HH_*
ELCSA_adult_*
ELCSA_adult_cat_*
ELCSA_full_*
ELCSA_full_cat_*
energy_*
femalehead_*
fert_DomRep_*
fert_loan_*
fert_oth_*
fert_PTTA_*
fert_purch_*
fert_spending_*
fertilizer_*
fstMonth_*
grossmargin_1_uc_*
group2_*
h_d_suplag*_*
h_d_suplag1_*
h_d_suplag2_*
h_d_suplag3_*
h_d_suplag4_*
h_d_suplag5_*
h_d_suplag6_*
h_sold_rice_*
h_sold_rice_uc_*
h_var1_*
h_var1_uc_*
h_var2_*
h_var2_uc_*
h_var3_*
h_var3_uc_*
h_var4_*
h_var4_uc_*
habitation_old_*
harv_any_hh_*
harv_lost_hh_*
harv_notyet_hh_*
harv_partial_hh_*
HDDS_*
HDDS_cat_*
HH_adults_*
HH_age_*
HH_atleast_allprim
HH_atleast_allsec
HH_atleast_someprim
HH_atleast_somesec
HH_children_*
HH_literacy
HH_literacy_*
hh_loss_pest_uc_*
HH_occupation
HH_occupation_*
HH_riceHaYear_*
HH_riceHaYear_uc_*
HH_valueHaYear_*
HH_valueHaYear_uc_*
hous_ind_*
house_own_*
HungerScale_*
HungerScale_cat_*
HungerScale_sev_*
ImprovedRice_*
income_*
input_spending_*
inputs_*
irrigate_spending_*
irrigated_*
labor_spending_*
lagoon_*
light_*
lime_*
livestock_income_*
margin_1_uc_*
months_insecure_*
n_allPlot_*
n_chicken_*
n_cow_*
n_culPlot_*
n_familylabor_*
n_goat_*
n_horse_*
n_instXplot1_uc_*
n_paidlabor_*
n_pig_*
n_riceplot_*
n_riceplot_uc_*
n_unpaidlabor_*
npk_*
npk_spending_*
nsm
obtloanamt_bank_*
obtloanamt_sara_*
other_harvest_value_*
other_income_*
other_sale_value_*
own_bicycle_*
own_car_*
own_cellphone_*
own_chicken_*
own_computer_*
own_cow_*
own_drying_*
own_elec_*
own_generator_*
own_goat_*
own_horse_*
own_landph_*
own_mill_*
own_motorcycle_*
own_pig_*
own_plough_*
own_refrig_*
own_tank_*
own_television_*
own_tiller_*
own_tractor_*
own_ventilator_*
own_wood_stove_*
pest_DomRep_*
pest_loan_*
pest_oth_*
pest_PTTA_*
pest_purch_*
pest_spending_*
pesticide_*
plan_arearice_*
plan_growrice_*
plan_loan_*
plan_numpar_*
plan15_newplotrice_*
profit_1_*
profit_1_uc_*
profit_2_uc_*
profit_vouch_2_uc*
profit_vouch_2_uc_*
qty_allchem_*
qty_allchem_kgha*
qty_allchem_kgha_uc_*
qty_npk_*
qty_urea_*
refloan_*
roof_*
rp_allchem_spending_uc_*
rp_allchem_totmore135_*
rp_allchem_totmore150_*
rp_allchem_uc_*
rp_compost_uc_*
rp_d_familylabor_*
rp_d_familylabor_uc_*
rp_d_paidlabor_*
rp_d_paidlabor_uc_*
rp_d_unpaidlabor_*
rp_d_unpaidlabor_uc_*
rp_fert_spending_uc_*
rp_fertilizer_uc_*
rp_h_d_3bagsulf_*
rp_h_d_3bagsulf_uc_*
rp_input_spending_uc*
rp_input_spending_uc_*
rp_inputs_uc_*
rp_irrigated_*
rp_labor_spending_*
rp_labor_spending_uc_*
rp_labor_spendingEX_uc_*
rp_n_familylabor_*
rp_n_familylabor_uc_*
rp_n_paidlabor_*
rp_n_paidlabor_uc_*
rp_n_unpaidlabor_*
rp_n_unpaidlabor_uc_*
rp_npk_spending_uc_*
rp_npk_uc_*
rp_pest_spending_uc_*
rp_pesticide_*
rp_pesticide_uc_*
rp_qty_allchem_uc_*
rp_qty_npk_uc_*
rp_qty_sulfate_uc_*
rp_qty_urea_uc_*
rp_seed_spending_uc_*
rp_spending_uc_*
rp_urea_spending_uc_*
rp_urea_uc_*
savings_fl_*
savings_st_*
seed_DomRep_*
seed_loan_*
seed_oth_*
seed_previous_*
seed_PTTA_*
seed_purch_*
seed_spending_*
seeds_ha2a_*
seeds_ha2a_cond_*
soil_*
t_harvest_std_kg_*
t_harvest_std_kg_uc_*
t_plot_area_*
t_plot_area_byins*1_uc*
t_plot_area_uc_*
t_plotRiceYield1_*
t_plotRiceYield1_uc_*
t_plotRiceYield5_1_uc*
t_plotRiceYield5_1_uc_*
t_prod_value_*
t_prod_value_uc_*
t_prod_value5_uc*
t_sale_std_kg_*
t_sale_std_kg_uc_*
t_sale_value_*
t_sale_value_uc_*
t_sizeculPlot_*
tech_3plant_*
tech_3plant_cond_*
thinkben_*
toilet_*
total_income_*
total_spending_*
treatment
trtXinfo
urea_*
urea_spending_*
wall_*
WDDS_*
WDDS_cat_*
workgroup_*
;


#delimit cr 


save panel_dataset_for_replication, replace 

stop 
 

informed
F_harv_any_hh_*
F_profit_2_c_*
F_profit_2_uc_*
F_rp_allchem_spending_uc_*
F_rp_labor_spendingEX_uc_*
F_rp_pest_spending_uc_*
F_t_plotRiceYield5_1_c*
F_t_plotRiceYield5_1_uc_*
F_t_prod_value5_uc_*
F_t_sale_value_uc_*
km_to_highway
profit_2_c_*
profit_2_uc
profit_vouch_2_c_*
rp_chempest_spending_uc_*
rp_chfert_pest_uc_*
rp_chfert_uc_*
t_plotRiceYield5_1_c*
t_plotRiceYield5_1_uc
treat_inf
treat_no_inf
